version: '3.8'

services:
  app:
    container_name: app-alessio
    build: .
    command: npm run serve
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /node_modules
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017/myappdb
      - JWT_SECRET='secret'

  mongo:
    container_name: mongodb-alessio
    image: mongo
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"

