version: '3.8'

services:
  app:
    container_name: app-alessio
    build: .
    ports:
      - "3000:3000"
    # volumes:
    #  - ./app:/usr/src/app
    depends_on:
      - mongo
    environment:
      - JWT_SECRET='secret'
      - DB_CONN=mongodb://mongo/familyeasy
    command: sh -c "node dbtest && node server.js"

  mongo:
    container_name: mongodb-alessio
    image: mongo
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"

volumes: 
  db-data: 

